// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230703171117_initalmigration")]
    partial class initalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.Property<int>("GroceryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grocerylist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroceryListID"));

                    b.Property<int>("HouseholdID")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.HasKey("GroceryListID");

                    b.ToTable("grocerylist");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListItemEntity", b =>
                {
                    b.Property<int>("GroceryListItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grocerylistitem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroceryListItemID"));

                    b.Property<int>("GroceryListID")
                        .HasColumnType("integer")
                        .HasColumnName("grocerylist_id");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("integer")
                        .HasColumnName("item_amount");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.HasKey("GroceryListItemID");

                    b.ToTable("grocerylist_item");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdEntity", b =>
                {
                    b.Property<int>("HouseholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HouseholdID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("HouseholdID");

                    b.ToTable("household");
                });
#pragma warning restore 612, 618
        }
    }
}
