// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230630233347_updateentities2")]
    partial class updateentities2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("household_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("household_id")
                        .IsUnique();

                    b.ToTable("grocery_list");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListItemEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("grocery_list_id")
                        .HasColumnType("integer");

                    b.Property<string>("item_amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("grocery_list_id");

                    b.ToTable("grocery_list_item");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("household");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.HasOne("Domain.Entities.HouseholdEntity", "household_")
                        .WithOne("grocery_list")
                        .HasForeignKey("Domain.Entities.GroceryListEntity", "household_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("household_");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListItemEntity", b =>
                {
                    b.HasOne("Domain.Entities.GroceryListEntity", "grocery_list_")
                        .WithMany("items")
                        .HasForeignKey("grocery_list_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("grocery_list_");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdEntity", b =>
                {
                    b.Navigation("grocery_list");
                });
#pragma warning restore 612, 618
        }
    }
}
