// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Data;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230703160641_initalmigration")]
    partial class initalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.Property<int>("GroceryListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grocerylist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroceryListID"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<int>("HouseholdID")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.HasKey("GroceryListID");

                    b.HasIndex("HouseholdID");

                    b.ToTable("grocerylist");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListItemEntity", b =>
                {
                    b.Property<int>("GroceryListItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grocerylistitem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroceryListItemID"));

                    b.Property<int?>("GroceryListEntityGroceryListID")
                        .HasColumnType("integer");

                    b.Property<int>("GroceryListID")
                        .HasColumnType("integer")
                        .HasColumnName("grocerylist_id");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("integer")
                        .HasColumnName("item_amount");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.HasKey("GroceryListItemID");

                    b.HasIndex("GroceryListEntityGroceryListID");

                    b.HasIndex("GroceryListID");

                    b.ToTable("grocerylist_item");
                });

            modelBuilder.Entity("Domain.Entities.HouseholdEntity", b =>
                {
                    b.Property<int>("HouseholdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HouseholdID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("HouseholdID");

                    b.ToTable("household");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.HasOne("Domain.Entities.HouseholdEntity", "household")
                        .WithMany()
                        .HasForeignKey("HouseholdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("household");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListItemEntity", b =>
                {
                    b.HasOne("Domain.Entities.GroceryListEntity", null)
                        .WithMany("grocerylist_items")
                        .HasForeignKey("GroceryListEntityGroceryListID");

                    b.HasOne("Domain.Entities.GroceryListEntity", "grocerylist")
                        .WithMany()
                        .HasForeignKey("GroceryListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("grocerylist");
                });

            modelBuilder.Entity("Domain.Entities.GroceryListEntity", b =>
                {
                    b.Navigation("grocerylist_items");
                });
#pragma warning restore 612, 618
        }
    }
}
