// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.DatabaseContext;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230807233250_initalmigration")]
    partial class initalmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.GroceryList.GroceryListEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_modified");

                    b.Property<int?>("household")
                        .HasColumnType("integer")
                        .HasColumnName("household");

                    b.HasKey("Id")
                        .HasName("pk_grocerylist");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_grocerylist_household_id");

                    b.HasIndex("household")
                        .IsUnique()
                        .HasDatabaseName("ix_grocerylist_household");

                    b.ToTable("grocerylist", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GroceryList.GroceryListItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<int>("GroceryListId")
                        .HasColumnType("integer")
                        .HasColumnName("grocery_list_id");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("integer")
                        .HasColumnName("item_amount");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_name");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_modified");

                    b.Property<int?>("grocerylist")
                        .HasColumnType("integer")
                        .HasColumnName("grocerylist");

                    b.HasKey("Id")
                        .HasName("pk_grocerylist_item");

                    b.HasIndex("GroceryListId")
                        .HasDatabaseName("ix_grocerylist_item_grocery_list_id");

                    b.HasIndex("grocerylist")
                        .HasDatabaseName("ix_grocerylist_item_grocerylist");

                    b.ToTable("grocerylist_item", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Household.HouseholdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_household");

                    b.ToTable("household", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GroceryList.GroceryListEntity", b =>
                {
                    b.HasOne("Domain.Entities.Household.HouseholdEntity", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grocerylist_household_household_id");

                    b.HasOne("Domain.Entities.Household.HouseholdEntity", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.GroceryList.GroceryListEntity", "household")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_grocerylist_household_household_entity_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Domain.Entities.GroceryList.GroceryListItemEntity", b =>
                {
                    b.HasOne("Domain.Entities.GroceryList.GroceryListEntity", "GroceryList")
                        .WithMany()
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grocerylist_item_grocerylist_grocery_list_id");

                    b.HasOne("Domain.Entities.GroceryList.GroceryListEntity", null)
                        .WithMany()
                        .HasForeignKey("grocerylist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_grocerylist_item_grocerylist_grocery_list_entity_id");

                    b.Navigation("GroceryList");
                });
#pragma warning restore 612, 618
        }
    }
}
