services:
  commandcentralapi:
    image: commandcentralapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on: 
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=commandcentraldb
      - POSTGRES_PASSWORD=commandcentralpass
      - POSTGRES_DB=commandcentral_db
