services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-commandcentralpass}
      POSTGRES_DB: ${POSTGRES_DB:-commandcental_db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  
  commandcentralapi:
    image: commandcentral_api
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:80
    depends_on: 
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres: